script:
- npm install asar -g
- npm install
- npm install bower grunt -g
- bower install
- grunt init
- "./build.sh"
deploy:
  provider: releases
  api_key:
    secure: I954i+HbgoRVDenCDfGkLliRV3PpQ26SSGhoiS4k+fzmrQ2eLnOCtk1ay5hlcsl9eUEDvm/XP8s5r0d3nykY3MMnTZjB6C4J52pYNJRKV836eEBChhofkCBhJ1L3lewbRkaicPEfdpGZL1RtDF+e6p1Q4G3VfwjcrHH84hv0BX8c7yPjw6WbYv7/UDyggta+iqoc0N9+6C8ak9xZRC4q1ZlXiA38GXGfFBeT6CJuk5Mhv1rmVt3O82tZ7/TLoy+iKAC4MCSRcPkoPnArULnGY6h7ZoLprfjKga8bZU8O1RG5o+udH2uYibo5jETO1pdHnLahW3QiWc4594B1vLiu33Jn1O8vZTjzZxMXkYrZ88bazUuHQWePit6Y8RKibE0QzVspqU69bVH9vvf3AjU9utSxXlQLvk2SgSSvZ3vWuW+rcWEpbhYJxYRZzY/ixV9lBXFDa/8kxgV9EjuHw/EFmtNzAY+AMliceMWHoFxIJ1c1Kkn2rFa8bMjGKbc6/LUxbfsH2fSJDjTMuPbVliN+mBsAfRUoWUsCAAQYBXb1Wgl80/hJYDy0ykOD+kZa1PLbY3mW7RW088p/bYULUPz4Iez6JjFbT3KQYicmnMU/2fwORuADHPt40ehDbEp+BTx/zY3FdlSfQdgV1xOIduzMq9I6ypRKuWLC/rN5Vluxyps=
  file: 
    - "./build/app.asar"
    - "./build/party-youtube-downloader-darwin.zip"
    - "./build/party-youtube-downloader-linux-ia32.zip"
    - "./build/party-youtube-downloader-linux-x64.zip"
    - "./build/party-youtube-downloader-windows-ia32.zip"
    - "./build/party-youtube-downloader-windows-x64.zip"
  on:
    repo: nemanjan00/party-youtube-downloader
    all_branches: true
    tags: true

